services:
  - type: web
    name: eventsync-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: AWS_REGION
        value: eu-north-1
      - key: AWS_BUCKET_NAME
        value: selfcheckin-storage
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "https://eventsync.vercel.app,https://eventsync.netlify.app,http://localhost:5173"
